name: ppo
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.9.11
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - pip
  - pip:
    - tqdm==4.66.5
    - wandb==0.18.3
    - pillow==11.0.0
    - ale-py==0.8.1
    - gymnasium==0.29.1
    - gymnasium[classic-control]==0.29.1
    - gymnasium[atari]==0.29.1
    - gymnasium[other]
    - gymnasium[accept-rom-license]